/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tpes;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author Dell
 */
public class chart extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(chart.class.getName());

    /**
     * Creates new form chart
     */
    public chart() {
        initComponents();
        // 1. Create Mock Data (Hardcoded values for testing)
DefaultPieDataset dataset = new DefaultPieDataset();
dataset.setValue("Excellent (9-10)", 15); // 15 students gave Excellent
dataset.setValue("Good (7-8)", 25);      // 25 students gave Good
dataset.setValue("Average (5-6)", 10);   // 10 students gave Average
dataset.setValue("Poor (Below 5)", 5);   // 5 students gave Poor

// 2. Create the Chart
JFreeChart chart = ChartFactory.createPieChart(
    "Teacher Performance Summary", 
    dataset, 
    true,   // Show Legend
    true,   // Show Tooltips
    false   // No URLs
);

// 3. Customizing Colors (Make it look professional)
PiePlot plot = (PiePlot) chart.getPlot();
plot.setSectionPaint("Excellent (9-10)", new Color(34, 139, 34)); // Dark Green
plot.setSectionPaint("Good (7-8)", new Color(50, 205, 50));      // Lime Green
plot.setSectionPaint("Average (5-6)", Color.ORANGE);
plot.setSectionPaint("Poor (Below 5)", Color.RED);

// 4. Display in your NetBeans JPanel
ChartPanel chartPanel = new ChartPanel(chart);
chartPanel.setPreferredSize(new java.awt.Dimension(400, 300));

// IMPORTANT: Set your JPanel layout to BorderLayout in NetBeans Design view first!
your_panel_name.removeAll();
your_panel_name.add(chartPanel, java.awt.BorderLayout.CENTER);
your_panel_name.validate();
your_panel_name.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        your_panel_name = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        your_panel_name.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(your_panel_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(your_panel_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new chart().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel your_panel_name;
    // End of variables declaration//GEN-END:variables
}
