/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tpes;

import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JRadioButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class form2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(form2.class.getName());
    private String ID;
    private String FullName;
    private int sub_id;
    private String t_id;
    private String teacher;
    private ArrayList teacherIds;
    private ArrayList subjectIds;
    private ArrayList teacherName;
    private int q1;
    private int q2;
    private int q3;
    private int q4;
    private int q5;
   
    public form2() {
        initComponents();
    }
    public form2(String ID, String name,int sub_id, String t_id, String teacher,int q1,int q2,int q3,int q4,int q5) {
        initComponents();
        TPES db=new TPES();
       ArrayList<String> teacherIds = new ArrayList<>();
       ArrayList<Integer> subjectIds = new ArrayList<>();
       ArrayList<String> teacherName = new ArrayList<>();
        studentid.setText(ID);
        teacher_name.setText(teacher);
        ResultSet rs;
        this.ID=ID;
        this.sub_id=sub_id;
        this.t_id=t_id;
        this.teacher=teacher;
        this.q1=q1;
        this.q2=q2;
        this.q3=q3;
        this.q4=q4;
        this.q5=q5;
        String dep="";
        int sem=0;
        ResultSet rs2;
        subject.removeAllItems(); // clear previous items
        subject.addItem("Select Subject");
try {
    rs = db.studentName(ID);
    if (rs.next()) {
        String fname = rs.getString("st_fname");
        String lname = rs.getString("st_lname");
        dep=rs.getString("st_dept");
        sem=Integer.parseInt(rs.getString("st_semester"));
        System.out.println(sem);

        fullname.setText(fname + " " + lname);
    }
    
    rs2 = db.subjects(sem, dep, ID);
    while(rs2.next()){
        subjectIds.add(Integer.parseInt(rs2.getString("sub_id")));
        String subName= rs2.getString("sub_name");
        teacherIds.add(rs2.getString("t_id"));
        String teacherFName=rs2.getString("t_fname");
        String teacherLName=rs2.getString("t_lname");
        String teacherFullName=teacherFName+" "+teacherLName;
        teacherName.add(teacherFullName);
        subject.addItem(subName);
        }
    
    
    
} catch(Exception e){
            System.out.println(e);
        }
        this.FullName=fullname.getText();
        this.subjectIds=subjectIds;
        this.teacherIds=teacherIds;
        this.teacherName=teacherName;
    }
    int Qmarks(JRadioButton qo1, JRadioButton qo2, JRadioButton qo3, JRadioButton qo4, JRadioButton qo5) {
    int q = 0; // Default or starting value
    
    if (qo1.isSelected()) q = 2;
    if (qo2.isSelected()) q = 4;
    if (qo3.isSelected()) q = 6;
    if (qo4.isSelected()) q = 8;
    if (qo5.isSelected()) q = 10;
    
    return q; // Return the updated value to the caller
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        o11 = new javax.swing.JRadioButton();
        o12 = new javax.swing.JRadioButton();
        o13 = new javax.swing.JRadioButton();
        o14 = new javax.swing.JRadioButton();
        o15 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        q6o2 = new javax.swing.JRadioButton();
        q6o1 = new javax.swing.JRadioButton();
        q6o3 = new javax.swing.JRadioButton();
        q6o4 = new javax.swing.JRadioButton();
        q6o5 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        studentid = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        q7o2 = new javax.swing.JRadioButton();
        q7o1 = new javax.swing.JRadioButton();
        q7o3 = new javax.swing.JRadioButton();
        q7o4 = new javax.swing.JRadioButton();
        q7o5 = new javax.swing.JRadioButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        q8o2 = new javax.swing.JRadioButton();
        q8o1 = new javax.swing.JRadioButton();
        q8o3 = new javax.swing.JRadioButton();
        q8o4 = new javax.swing.JRadioButton();
        q8o5 = new javax.swing.JRadioButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        q9o2 = new javax.swing.JRadioButton();
        q9o1 = new javax.swing.JRadioButton();
        q9o3 = new javax.swing.JRadioButton();
        q9o4 = new javax.swing.JRadioButton();
        q9o5 = new javax.swing.JRadioButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        q10o2 = new javax.swing.JRadioButton();
        q10o1 = new javax.swing.JRadioButton();
        q10o3 = new javax.swing.JRadioButton();
        q10o4 = new javax.swing.JRadioButton();
        q10o5 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        subject = new javax.swing.JComboBox<>();
        confirm = new javax.swing.JButton();
        teacher_name = new javax.swing.JLabel();

        jPanel9.setBackground(new java.awt.Color(57, 77, 120));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("6. How strong are the teacher’s communication skills?");

        buttonGroup1.add(o11);
        o11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        o11.setForeground(new java.awt.Color(255, 255, 255));
        o11.setText("2");
        o11.addActionListener(this::o11ActionPerformed);

        buttonGroup1.add(o12);
        o12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        o12.setForeground(new java.awt.Color(255, 255, 255));
        o12.setText("1");

        buttonGroup1.add(o13);
        o13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        o13.setForeground(new java.awt.Color(255, 255, 255));
        o13.setText("3");

        buttonGroup1.add(o14);
        o14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        o14.setForeground(new java.awt.Color(255, 255, 255));
        o14.setText("4");

        buttonGroup1.add(o15);
        o15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        o15.setForeground(new java.awt.Color(255, 255, 255));
        o15.setText("5");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(o12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(o11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(o13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(o14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(o15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(o12)
                    .addComponent(o11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o13, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o15)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(70, 80, 90));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("6. How strong are the teacher’s communication skills?");

        buttonGroup1.add(q6o2);
        q6o2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q6o2.setForeground(new java.awt.Color(255, 255, 255));
        q6o2.setText("2");
        q6o2.addActionListener(this::q6o2ActionPerformed);

        buttonGroup1.add(q6o1);
        q6o1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q6o1.setForeground(new java.awt.Color(255, 255, 255));
        q6o1.setText("1");

        buttonGroup1.add(q6o3);
        q6o3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q6o3.setForeground(new java.awt.Color(255, 255, 255));
        q6o3.setText("3");

        buttonGroup1.add(q6o4);
        q6o4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q6o4.setForeground(new java.awt.Color(255, 255, 255));
        q6o4.setText("4");

        buttonGroup1.add(q6o5);
        q6o5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q6o5.setForeground(new java.awt.Color(255, 255, 255));
        q6o5.setText("5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(q6o1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(q6o2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(q6o3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(q6o4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(q6o5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q6o1)
                    .addComponent(q6o2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q6o3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q6o4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q6o5)))
        );

        jLabel4.setBackground(new java.awt.Color(0, 0, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/Done.png"))); // NOI18N
        jLabel4.setText("CONFIRM");

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 33, 71));
        jLabel3.setText("STUDENT CENTER");

        fullname.setEditable(false);
        fullname.setBackground(new java.awt.Color(57, 77, 120));
        fullname.setFont(new java.awt.Font("Arial Unicode MS", 3, 14)); // NOI18N
        fullname.setForeground(new java.awt.Color(255, 255, 255));
        fullname.setBorder(null);
        fullname.addActionListener(this::fullnameActionPerformed);

        studentid.setBackground(new java.awt.Color(57, 77, 120));
        studentid.setFont(new java.awt.Font("Arial Unicode MS", 3, 14)); // NOI18N
        studentid.setForeground(new java.awt.Color(255, 255, 255));
        studentid.setBorder(null);

        jPanel8.setBackground(new java.awt.Color(70, 80, 90));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("7. How fair is the teacher in grading and assessment?");

        buttonGroup2.add(q7o2);
        q7o2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q7o2.setForeground(new java.awt.Color(255, 255, 255));
        q7o2.setText("2");
        q7o2.addActionListener(this::q7o2ActionPerformed);

        buttonGroup2.add(q7o1);
        q7o1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q7o1.setForeground(new java.awt.Color(255, 255, 255));
        q7o1.setText("1");

        buttonGroup2.add(q7o3);
        q7o3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q7o3.setForeground(new java.awt.Color(255, 255, 255));
        q7o3.setText("3");

        buttonGroup2.add(q7o4);
        q7o4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q7o4.setForeground(new java.awt.Color(255, 255, 255));
        q7o4.setText("4");

        buttonGroup2.add(q7o5);
        q7o5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q7o5.setForeground(new java.awt.Color(255, 255, 255));
        q7o5.setText("5");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(q7o1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(q7o2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(q7o3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(q7o4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(q7o5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q7o1)
                    .addComponent(q7o2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q7o3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q7o4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q7o5)))
        );

        jPanel12.setBackground(new java.awt.Color(70, 80, 90));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("8. How professional is the teacher’s behavior and attitude?");

        buttonGroup3.add(q8o2);
        q8o2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q8o2.setForeground(new java.awt.Color(255, 255, 255));
        q8o2.setText("2");
        q8o2.addActionListener(this::q8o2ActionPerformed);

        buttonGroup3.add(q8o1);
        q8o1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q8o1.setForeground(new java.awt.Color(255, 255, 255));
        q8o1.setText("1");

        buttonGroup3.add(q8o3);
        q8o3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q8o3.setForeground(new java.awt.Color(255, 255, 255));
        q8o3.setText("3");

        buttonGroup3.add(q8o4);
        q8o4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q8o4.setForeground(new java.awt.Color(255, 255, 255));
        q8o4.setText("4");

        buttonGroup3.add(q8o5);
        q8o5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q8o5.setForeground(new java.awt.Color(255, 255, 255));
        q8o5.setText("5");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(q8o1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(q8o2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(q8o3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(q8o4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(q8o5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q8o1)
                    .addComponent(q8o2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q8o3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q8o4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q8o5)))
        );

        jPanel13.setBackground(new java.awt.Color(70, 80, 90));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("9. How well does the teacher cover the syllabus?");

        buttonGroup4.add(q9o2);
        q9o2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q9o2.setForeground(new java.awt.Color(255, 255, 255));
        q9o2.setText("2");
        q9o2.addActionListener(this::q9o2ActionPerformed);

        buttonGroup4.add(q9o1);
        q9o1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q9o1.setForeground(new java.awt.Color(255, 255, 255));
        q9o1.setText("1");

        buttonGroup4.add(q9o3);
        q9o3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q9o3.setForeground(new java.awt.Color(255, 255, 255));
        q9o3.setText("3");

        buttonGroup4.add(q9o4);
        q9o4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q9o4.setForeground(new java.awt.Color(255, 255, 255));
        q9o4.setText("4");

        buttonGroup4.add(q9o5);
        q9o5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q9o5.setForeground(new java.awt.Color(255, 255, 255));
        q9o5.setText("5");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(q9o1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(q9o2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(q9o3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(q9o4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(q9o5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q9o1)
                    .addComponent(q9o2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q9o3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q9o4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q9o5)))
        );

        jPanel14.setBackground(new java.awt.Color(70, 80, 90));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel19.setBackground(new java.awt.Color(70, 80, 90));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("10. Overall, how satisfied are you with this teacher’s performance?");

        buttonGroup5.add(q10o2);
        q10o2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q10o2.setForeground(new java.awt.Color(255, 255, 255));
        q10o2.setText("2");
        q10o2.addActionListener(this::q10o2ActionPerformed);

        buttonGroup5.add(q10o1);
        q10o1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q10o1.setForeground(new java.awt.Color(255, 255, 255));
        q10o1.setText("1");

        buttonGroup5.add(q10o3);
        q10o3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q10o3.setForeground(new java.awt.Color(255, 255, 255));
        q10o3.setText("3");

        buttonGroup5.add(q10o4);
        q10o4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q10o4.setForeground(new java.awt.Color(255, 255, 255));
        q10o4.setText("4");

        buttonGroup5.add(q10o5);
        q10o5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q10o5.setForeground(new java.awt.Color(255, 255, 255));
        q10o5.setText("5");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(q10o1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(q10o2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(q10o3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(q10o4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(q10o5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q10o1)
                    .addComponent(q10o2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q10o3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q10o4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q10o5)))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/Left 2.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        submit.setBackground(new java.awt.Color(0, 153, 204));
        submit.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("SUBMIT");
        submit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        submit.setBorderPainted(false);
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        submit.setDoubleBuffered(true);
        submit.addActionListener(this::submitActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(72, 72, 72)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(2, 2, 2)
                                .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(348, 348, 348)))))
                .addGap(191, 191, 191)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 680, 460));

        jPanel1.setBackground(new java.awt.Color(0, 33, 71));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TPES");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/Home.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/TPESlogo.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/Male User.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 519, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel2)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 130));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel11.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Select a Subject");

        subject.setBackground(new java.awt.Color(204, 204, 204));
        subject.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select---" }));
        subject.addActionListener(this::subjectActionPerformed);

        confirm.setBackground(new java.awt.Color(0, 0, 255));
        confirm.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("Fill Form");
        confirm.addActionListener(this::confirmActionPerformed);

        teacher_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        teacher_name.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(teacher_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(confirm))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(teacher_name, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void q6o2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6o2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q6o2ActionPerformed

    private void q7o2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7o2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q7o2ActionPerformed

    private void o11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o11ActionPerformed

    private void q8o2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8o2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q8o2ActionPerformed

    private void q9o2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9o2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q9o2ActionPerformed

    private void q10o2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q10o2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q10o2ActionPerformed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        form1 l=new form1();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MousePressed

    
    /*
     public class SubjectItem {
    private int subId;
    private String subName;

    public SubjectItem(int id, String name) {
        this.subId = id;
        this.subName = name;
    }

    public int getSubId() { return subId; }

    @Override
    public String toString() {
        return subName; 
    }
}*/
    
    
    /*
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {                                       
    TPES db = new TPES();

// 1. Check if the default "Select Subject" or nothing is selected
    Object selectedItem = subject.getSelectedItem();
    if (selectedItem == null || selectedItem instanceof String) {
        JOptionPane.showMessageDialog(this, "Please select a valid subject");
        return;
    }
    if(buttonGroup1.getSelection()==null || buttonGroup2.getSelection()==null || 
       buttonGroup3.getSelection()==null || buttonGroup4.getSelection()==null || 
       buttonGroup5.getSelection()==null){
        JOptionPane.showMessageDialog(this, "Please Select all the options");
    }
    else {
        SubjectItem selected = (SubjectItem) selectedItem;
        int current_sub_id = selected.getSubId(); 

        int q6=Qmarks(q6o1,q6o2,q6o3,q6o4,q6o5);
        int q7=Qmarks(q7o1,q7o2,q7o3,q7o4,q7o5);
        int q8=Qmarks(q8o1,q8o2,q8o3,q8o4,q8o5);
        int q9=Qmarks(q9o1,q9o2,q9o3,q9o4,q9o5);
        int q10=Qmarks(q10o1,q10o2,q10o3,q10o4,q10o5);
        int total = q1+q2+q3+q4+q5+q6+q7+q8+q9+q10;

        // 5. Submit to DB using the ID from the class
        if(db.feedback(ID, current_sub_id, t_id, q1, q2, q3, q4, q5, q6, q7, q8, q9, q10, total) == 1){
            JOptionPane.showMessageDialog(this, "Your feedback has been added");
            Std_home h = new Std_home(ID);
            h.setVisible(true);
            dispose();
        }
    }
}

    */
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
          TPES db=new TPES();
          if(buttonGroup1.getSelection()==null || buttonGroup2.getSelection()==null || buttonGroup3.getSelection()==null || buttonGroup4.getSelection()==null || buttonGroup5.getSelection()==null){
        JOptionPane.showMessageDialog(this, "Please Select all the options");
        }
        else{
        int q6=Qmarks(q6o1,q6o2,q6o3,q6o4,q6o5);
        int q7=Qmarks(q7o1,q7o2,q7o3,q7o4,q7o5);
        int q8=Qmarks(q8o1,q8o2,q8o3,q8o4,q8o5);
        int q9=Qmarks(q9o1,q9o2,q9o3,q9o4,q9o5);
        int q10=Qmarks(q10o1,q10o2,q10o3,q10o4,q10o5);
        int total=q1+q2+q3+q4+q5+q6+q7+q8+q9+q10;
        if(db.feedback(ID, sub_id, t_id, q1, q2, q3, q4, q5, q6, q7, q8, q9, q10, total)==1){
        JOptionPane.showMessageDialog(this, "Your feedback has been added");
        Std_home h=new Std_home(ID);
        h.setVisible(true);
        dispose();
        }
          }
    }//GEN-LAST:event_submitActionPerformed

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        int selectedIndex = subject.getSelectedIndex();
        if(subject.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Please select a subject");
        }
        else{
            String selectedTeacherId =teacherIds.get(selectedIndex-1).toString();
            int selectedSubjectId =Integer.parseInt(subjectIds.get(selectedIndex-1).toString());
            String selectedTeacherName =teacherName.get(selectedIndex-1).toString();
            form1 f=new form1(ID,FullName,selectedSubjectId,selectedTeacherId,selectedTeacherName);
            f.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new form2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton o11;
    private javax.swing.JRadioButton o12;
    private javax.swing.JRadioButton o13;
    private javax.swing.JRadioButton o14;
    private javax.swing.JRadioButton o15;
    private javax.swing.JRadioButton q10o1;
    private javax.swing.JRadioButton q10o2;
    private javax.swing.JRadioButton q10o3;
    private javax.swing.JRadioButton q10o4;
    private javax.swing.JRadioButton q10o5;
    private javax.swing.JRadioButton q6o1;
    private javax.swing.JRadioButton q6o2;
    private javax.swing.JRadioButton q6o3;
    private javax.swing.JRadioButton q6o4;
    private javax.swing.JRadioButton q6o5;
    private javax.swing.JRadioButton q7o1;
    private javax.swing.JRadioButton q7o2;
    private javax.swing.JRadioButton q7o3;
    private javax.swing.JRadioButton q7o4;
    private javax.swing.JRadioButton q7o5;
    private javax.swing.JRadioButton q8o1;
    private javax.swing.JRadioButton q8o2;
    private javax.swing.JRadioButton q8o3;
    private javax.swing.JRadioButton q8o4;
    private javax.swing.JRadioButton q8o5;
    private javax.swing.JRadioButton q9o1;
    private javax.swing.JRadioButton q9o2;
    private javax.swing.JRadioButton q9o3;
    private javax.swing.JRadioButton q9o4;
    private javax.swing.JRadioButton q9o5;
    private javax.swing.JTextField studentid;
    private javax.swing.JComboBox<String> subject;
    private javax.swing.JButton submit;
    private javax.swing.JLabel teacher_name;
    // End of variables declaration//GEN-END:variables
}
